import { Outfit } from "next/font/google";
import "./globals.css";
import Header from "./_component/Header";
import Footer from "./_component/Footer";

const outfit = Outfit({
  
  subsets: ["latin"],
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${outfit.className}  antialiased`}
      >
        <div >
          <Header />
          {/* <div className="md:px-10"> */}
            {children}
          {/* </div> */}
          
          <Footer />

        </div>
      </body>
    </html>
  );
}
